# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: dfb0404
_src_path: https://github.com/qiime2/q2-setup-template.git
module_name: quality_control
plugin_name: q2_quality_control
plugin_scripts: q2_quality_control/decontam_assets/run_decontam.R
project_author_email: nbokulich@gmail.com, jordenrabasco1@gmail.com
project_author_name: Nicholas Bokulich and Jorden Rabasco
project_description: Quality control methods for feature and sequence data.
project_name: q2-quality-control
project_urls_homepage: https://github.com/qiime2/q2-quality-control
project_urls_repository: https://github.com/qiime2/q2-quality-control
